### PR TITLE
Verify that @fidian is the new maintainer

### PR DESCRIPTION
**Pull request by mlafeldt**
I hereby verify that I transferred ownership of tomdoc.sh to Tyler Akins (@fidian). He's the new maintainer of the project and https://github.com/tests-always-included/tomdoc.sh is the official new home.

-Mathias

### CODE REVIEW

**Comment by mlafeldt** [comment]
@fidian Here's a signed (and empty) commit verifying that you're the new maintainer. We can use it to prove that this is the genuine new home of tomdoc.sh.

**Comment by fidian** [comment]
I love this idea.  Do you have a public GPG key?  Did you want to cryptographically sign the message as well?

**Comment by mlafeldt** [comment]
This commit is already signed. Just click on the green *Verified* icon. Then you'll also see my GPG key.

Merge this and we're done. :)

**Comment by fidian** [comment]
It took me a while to notice that *Verified* button.  Wonderful!  Thank you again!

**Pull request merged**
